baseURL = "https://kybervpk.fi"
title = "KyberVPK"
theme = "kvpk"

defaultContentLanguage = "fi"
[languages]
  [languages.fi]
    weight = 1
    contentDir = "content/fi"
    languageCode = "fi-fi"
    languageName = "suomi"
    [languages.fi.params]
      linkText = "Suomeksi"

  [languages.en]
    weight = 3
    contentDir = "content/en"
    languageCode = "en-gb"
    languageName = "English"
    [languages.en.params]
      linkText = "In English"
